### ISSUE TITLE
OutWiker 2.0.0.794 dev crashes on start

### ISSUE THREAD

**Issue by bl00dy1837** [Jenyay/outwiker#19]
OS:
debian stretch/sid

Version:
OutWiker 2.0.0.794 dev

Traceback (most recent call last):
  File "runoutwiker.py", line 105, in <module>
    outwiker = OutWiker(False)
  File "runoutwiker.py", line 35, in __init__
    wx.App.__init__ (self, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "runoutwiker.py", line 70, in OnInit
    starter.processGUI()
  File "/usr/share/outwiker/outwiker/core/starter.py", line 33, in processGUI
    self.__openRecentWiki ()
  File "/usr/share/outwiker/outwiker/core/starter.py", line 79, in __openRecentWiki
    openWiki (Application.recentWiki[0])
  File "/usr/share/outwiker/outwiker/core/commands.py", line 172, in openWiki
    Application.wikiroot = result
  File "/usr/share/outwiker/outwiker/core/application.py", line 320, in wikiroot
    self.onWikiOpen (self.__wikiroot)
  File "/usr/share/outwiker/outwiker/core/event.py", line 60, in __call__
    handler[0](*args, **kargs)
  File "/usr/share/outwiker/outwiker/gui/tabscontroller.py", line 260, in __onWikiOpen
    self.__loadTabs(root)
  File "/usr/share/outwiker/outwiker/gui/tabscontroller.py", line 232, in __loadTabs
    self._application.selectedPage = self._tabsCtrl.GetPage (selectedTab)
  File "/usr/share/outwiker/outwiker/core/application.py", line 388, in selectedPage
    self.__wikiroot.selectedPage = page
  File "/usr/share/outwiker/outwiker/core/tree.py", line 386, in selectedPage
    self.root.onPageSelect(self._selectedPage)
  File "/usr/share/outwiker/outwiker/core/event.py", line 60, in __call__
    handler[0](*args, **kargs)
  File "/usr/share/outwiker/outwiker/core/event.py", line 60, in __call__
    handler[0](*args, **kargs)
  File "/usr/share/outwiker/outwiker/gui/currentpagepanel.py", line 92, in __onPageSelect
    self.__updatePageView (page)
  File "/usr/share/outwiker/outwiker/gui/currentpagepanel.py", line 125, in __updatePageView
    self.__createPageView(page)
  File "/usr/share/outwiker/outwiker/gui/currentpagepanel.py", line 142, in __createPageView
    pageView = factory.getPageView (self)
  File "/usr/share/outwiker/outwiker/pages/wiki/wikipage.py", line 71, in getPageView
    return WikiPageView (parent)
  File "/usr/share/outwiker/outwiker/pages/wiki/wikipageview.py", line 34, in __init__
    super (WikiPageView, self).__init__ (parent)
  File "/usr/share/outwiker/outwiker/pages/wiki/basewikipageview.py", line 25, in __init__
    super (BaseWikiPageView, self).__init__ (parent, *args, **kwds)
  File "/usr/share/outwiker/outwiker/pages/html/basehtmlpanel.py", line 53, in __init__
    self.htmlWindow = getOS().getHtmlRender (self.notebook)
  File "/usr/share/outwiker/outwiker/core/system.py", line 212, in getHtmlRender
    return HtmlRenderWebKit (parent)
  File "/usr/share/outwiker/outwiker/gui/htmlrenderwebkit.py", line 44, in __init__
    import wx.html2 as webview
ImportError: No module named html2
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
PyAssertionError: C++ assertion "GetEventHandler() == this" failed at ../src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
wx._core.PyAssertionError: C++ assertion "GetEventHandler() == this" failed at ../src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

**Comment by Jenyay** [comment]
Похоже, не установлен пакет libwxgtk-webview3.0

**Comment by bl00dy1837** [comment]
sorry i dont understand russian.

i installed the package python-wxgtk-webview3.0, and now it works fine. thx
