### ISSUE TITLE
WebPage. Ошибка импорта локального файла в Windows

### ISSUE THREAD

**Issue by Jenyay** [Jenyay/outwiker#343]
Лог выглядит следующим образом:

```
2017-04-03 16:34:00 - START
Exception in thread Thread-207:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
  File "D:\Soft\OutWiker\plugins\webpage\gui\downloaddialog.py", line 311, in run
    downloader.start(self._url, controller)
  File "D:\Soft\OutWiker\plugins\webpage\downloader.py", line 60, in start
    obj = self.download(url)
  File "D:\Soft\OutWiker\plugins\webpage\downloader.py", line 32, in download
    response = opener.open(url, timeout=self._timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
  File "C:\Python27\lib\urllib2.py", line 449, in _open
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
  File "C:\Python27\lib\urllib2.py", line 1335, in file_open
  File "C:\Python27\lib\urllib2.py", line 1351, in open_local_file
ImportError: No module named email.utils
```

**Comment by Jenyay** [comment]
Проблема в том, что в сборке под Windows нет модулей email.utils и mimetypes, которые импортируются в методе open_local_file внутри urllib2.
