### ISSUE TITLE
Падает при запуске на Fedora 25

### ISSUE THREAD

**Issue by live2son** [Jenyay/outwiker#352]
$ python --version
Python 2.7.13

# pip install wxPython
Requirement already satisfied: wxPython in /usr/lib64/python2.7/site-packages/wx-3.0-gtk3

$ uname -a
Linux boxw 4.11.3-202.fc25.x86_64 #1 SMP Mon Jun 5 16:38:21 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

[~/outwiker/src]
$ python2.7 runoutwiker.py 
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_set_qdata: assertion 'node != NULL' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: cannot register existing type 'GtkWidget'
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: cannot register existing type 'GtkBuildable'
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_once_init_leave: assertion 'result != 0' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_register_static: assertion 'parent_type > 0' failed
  from gtk import _gtk

**Comment by Jenyay** [comment]
Сейчас в PyPi находится wxPython 4.0 alpha3, а OutWiker требуется wxPython 3.0.2. Скорее всего его надо устанавливать из пакетов репозитория дистрибутива.

**Comment by live2son** [comment]
Как раз wxPython 3.0.2 и установлен.

> $ pip show wxPython
Name: wxPython
Version: 3.0.2.0
Summary: Cross platform GUI toolkit for Python
Home-page: http://wxPython.org/
Author: Robin Dunn
Author-email: Robin Dunn <robin@alldunn.com>
License: wxWidgets Library License (LGPL derivative)
Location: /usr/lib64/python2.7/site-packages/wx-3.0-gtk3

**Comment by live2son** [comment]
К сожалению и предыдущая версия не запускается (

> [outwiker-release_1.9.0.790/src] $ python runoutwiker.py 
Traceback (most recent call last):
  File "runoutwiker.py", line 12, in <module>
    wxversion.select(WX_VERSION)
  File "/usr/lib64/python2.7/site-packages/wxversion.py", line 152, in select
    raise VersionError("Requested version of wxPython not found")
wxversion.VersionError: Requested version of wxPython not found

**Comment by Jenyay** [comment]
Со старой версией понятно - там требовался wxPython 2.8. Странно, что не запускается новая версия. А webkitgtk установлен (в Ubuntu этот пакет называется libwxgtk-webview3.0)?

**Comment by live2son** [comment]
Доброго времени суток, уважаемый разработчик! webkitgtk установлен. Клонирована свежайшая версия с github.При запуске выпадают ошибки и висит, но графического окна не появляется, завершаю по Cntrl+C.Вывод при запуске из терминала:[localhost outwiker]$ python src/runoutwiker.py/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed  from gtk import _gtk/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_set_qdata: assertion 'node != NULL' failed  from gtk import _gtk/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: cannot register existing type 'GtkWidget'  from gtk import _gtk/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed  from gtk import _gtk/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: cannot register existing type 'GtkBuildable'  from gtk import _gtk/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed  from gtk import _gtk/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_once_init_leave: assertion 'result != 0' failed  from gtk import _gtk/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_register_static: assertion 'parent_type > 0' failed  from gtk import _gtk^C     15.06.2017, 21:17, "Eugeniy Ilin" <notifications@github.com>:Со старой версией понятно - там требовался wxPython 2.8. Странно, что не запускается новая версия. А webkitgtk установлен (в Ubuntu этот пакет называется libwxgtk-webview3.0)?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by lesovsky** [comment]
такая же фигня, при запуске через `fab run` висит с ошибкой что не может подгрузить либу:
```
[localhost] local: LD_PRELOAD=libwx_gtk2u_webview-3.0.so.0 python2.7 runoutwiker.py 
ERROR: ld.so: object 'libwx_gtk2u_webview-3.0.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_set_qdata: assertion 'node != NULL' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: cannot register existing type 'GtkWidget'
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: cannot register existing type 'GtkBuildable'
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_once_init_leave: assertion 'result != 0' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_register_static: assertion 'parent_type > 0' failed
  from gtk import _gtk
^C
Stopped.
```
Либа с таким именем есть в пакете compat-wxGTK3-gtk2, пробовал подсунуть ее через симлинк --
 не взлетело.
(пакеты которые устанавливались wxGTK3 wxGTK wxPython python2-pillow python-enchant python-appindicator pygtk2 ibus-gtk2 ibus-pygtk2 fabric)

**Comment by paulelms** [comment]
Такая же проблема в Alt Linux, версии пакетов:

➜  src rpm -qa G wx             
libwxGTK3.0-gl-3.0.3-alt10.x86_64
libwxGTK3.0-3.0.3-alt10.x86_64
libwxGTK3.0-media-3.0.3-alt10.x86_64
libwxBase3.0-3.0.3-alt10.x86_64
python-module-wx3.0-3.0.2.0-alt1.1.x86_64

Выхлоп:

➜  src python ./runoutwiker.py
`
/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_core.py:16629: UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_set_qdata: assertion 'node != NULL' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: cannot register existing type 'GtkWidget'
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: cannot register existing type 'GtkBuildable'
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_once_init_leave: assertion 'result != 0' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_register_static: assertion 'parent_type > 0' failed
  from gtk import _gtk
`

Далее приложение висит как будто запущено, но нет никакого UI.
