### ISSUE TITLE
не запускается из "source code"

### ISSUE THREAD

**Issue by vadrer** [Jenyay/outwiker#369]
во-первых, в инструкции написано

To run the OutWiker program from source code, execute following command (in the src directory):
python outwiker.py

в папке `src`  вижу `runoutwiker.py`,

далее,

C:\vad\outwiker\src> python runoutwiker.py
Traceback (most recent call last):
  File "runoutwiker.py", line 107, in <module>
    outwiker = OutWiker(False)
  File "runoutwiker.py", line 29, in __init__
    wx.App.__init__(self, *args, **kwds)
  File "C:\apps\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7981, in __init__
    self._BootstrapApp()
  File "C:\apps\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7555, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "runoutwiker.py", line 72, in OnInit
    self.mainWnd.createGui()
  File "C:\vad\outwiker\src\outwiker\gui\mainwindow.py", line 160, in createGui
    self.__addActionsGui()
  File "C:\vad\outwiker\src\outwiker\gui\mainwindow.py", line 400, in __addActionsGui
    self.__createFileMenu()
  File "C:\vad\outwiker\src\outwiker\gui\mainwindow.py", line 207, in __createFileMenu
    True)
  File "C:\vad\outwiker\src\outwiker\gui\actioncontroller.py", line 215, in appendToolbarButton
    fullUpdate)
  File "C:\vad\outwiker\src\outwiker\gui\actioncontroller.py", line 334, in _appendToolbarItem
    self._actionsInfo[strid].toolItemId = toolbarItem.GetId()
AttributeError: 'NoneType' object has no attribute 'GetId'

wx только что скачал с кузницы, wxPython2.8-win32-unicode-2.8.12.1-py27.exe,
также установил зависимости:

C:\apps\Python27\Scripts>pip list
asn1crypto (0.23.0)
bcrypt (3.1.4)
cffi (1.11.2)
comtypes (1.1.3)
cryptography (2.1.3)
enum34 (1.1.6)
Fabric (1.13.2)
future (0.16.0)
idna (2.6)
ipaddress (1.0.18)
olefile (0.44)
paramiko (2.4.0)
PIL (1.1.7)
Pillow (4.0.0)
pip (9.0.1)
pyasn1 (0.4.2)
pycparser (2.18)
pyenchant (1.6.8)
PyInstaller (3.2.1)
PyNaCl (1.2.0)
pyperl (1.0)
pypiwin32 (219)
setuptools (28.8.0)
six (1.11.0)

что поделать, как починить?

**Comment by Jenyay** [comment]
wxPython должен быть версии 3.0.2, а не 2.8.

**Comment by vadrer** [comment]
с 3.0.2 заработало...
получается - в инструкции версии указаны неправильно??

**Comment by Jenyay** [comment]
@vadrer Возможно. Инструкция на странице программы или в документации?

**Comment by vadrer** [comment]
outwiker\src\help\help_ru\For programmers\Running from sources\__page.text
 outwiker\src\help\help_en\For Programmers\Starting from the Source Code\__page.text

**Comment by Jenyay** [comment]
@vadrer Понятно, спасибо, поправлю.

**Comment by Jenyay** [comment]
Исправил документацию.
