### ISSUE TITLE
updatenotifier 2.2 doesn't work with outwiker 3.0.0+846

### ISSUE THREAD

**Issue by adeptg** [Jenyay/outwiker#464]
In logs:

Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "threading.py", line 862, in run
  File "src/outwiker/gui/longprocessrunner.py", line 50, in <lambda>
  File "/home/adept/.config/outwiker/plugins/updatenotifier/updatecontroller.py", line 292, in _threadFunc
    in self._getUrlsForInstaller().items()
  File "/home/adept/.config/outwiker/plugins/updatenotifier/updatecontroller.py", line 320, in _getUrlsForInstaller
    self._installerPlugins = json.loads(pluginsRepo)
  File "json/__init__.py", line 312, in loads
TypeError: the JSON object must be str, not 'bytes'

Short proof:
>>> json_url = r"https://jenyay.net/uploads/Outwiker/Plugins/plugins.json"
>>> class NormalLoader(object):
...     def load(self, url):
...         if os.path.isfile(url):
...             return readTextFile(url)
...         fp = urllib.request.urlopen(url,timeout=10)
...         text = None
...         try:
...             text = fp.read()
...         finally:
...             fp.close()
...         return text
... 
>>> pluginsRepo = NormalLoader().load(json_url)
>>> a = json.loads(pluginsRepo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

>>> type(pluginsRepo)
<class 'bytes'>

$ python3 --version
Python 3.5.2

**Comment by adeptg** [comment]
Probably add decode to loaders.py will fix issue
text = fp.read().decode("utf-8")

**Comment by Jenyay** [comment]
@adeptg Thank you. fp.read().decode("utf-8") is solution. 

Not immediately able to repeat the bug, because it appears only in Python 3.5 but not in Python 3.6.
