### ISSUE TITLE
Install Error From Source

### ISSUE THREAD

**Issue by KitchM** [Jenyay/outwiker#480]
I am attempting to install on Fedora.  I get the following error:

sudo python runoutwiker.py
Traceback (most recent call last):
  File "runoutwiker.py", line 8, in <module>
    from outwiker.core.application import Application
  File "/home/xxx/outwiker/src/outwiker/core/application.py", line 5, in <module>
    from outwiker.core.config import Config
  File "/home/xxx/outwiker/src/outwiker/core/config.py", line 130
    class BaseOption(object, metaclass=ABCMeta):
                                      ^
SyntaxError: invalid syntax

What should be done?

Thanks.

**Comment by Jenyay** [comment]
What version of python is used? Most likely you are using Python 2.7, but you need to use Python 3.5 or later.

**Comment by KitchM** [comment]
I just installed Python 3.7.1 and verified it is there.  Then reran command and got:
Traceback (most recent call last):
  File "runoutwiker.py", line 8, in <module>
    from outwiker.core.application import Application
  File "/home/xxx/outwiker/src/outwiker/core/application.py", line 5, in <module>
    from outwiker.core.config import Config
  File "/home/xxx/outwiker/src/outwiker/core/config.py", line 130
    class BaseOption(object, metaclass=ABCMeta):
                                      ^
SyntaxError: invalid syntax

Looks like same error message.

**Comment by Jenyay** [comment]
Try python3 instead of python:

python3 runoutwiker.py

sudo not required

**Comment by KitchM** [comment]
I ran python3 runoutwiker.py from /home/xxx/outwiker/src/

Traceback (most recent call last):
  File "runoutwiker.py", line 8, in <module>
    from outwiker.core.application import Application
  File "/home/xxx/outwiker/src/outwiker/core/application.py", line 9, in <module>
    from outwiker.core.pluginsloader import PluginsLoader
  File "/home/xxx/outwiker/src/outwiker/core/pluginsloader.py", line 22, in <module>
    from outwiker.core.pluginbase import Plugin, InvalidPlugin
  File "/home/xxx/outwiker/src/outwiker/core/pluginbase.py", line 8, in <module>
    from outwiker.core.i18n import getLanguageFromConfig, loadLanguage
  File "/home/xxx/outwiker/src/outwiker/core/i18n.py", line 9, in <module>
    import wx
ImportError: No module named 'wx'

**Comment by Jenyay** [comment]
OK, That's better. Now you need to install the required libraries. wxPython 4.0.6, Pillow 6.0.0, hunspell 0.5.5, idna 2.8.

You can use pipenv to create virtual environment. 

Go to /home/xxx/outwiker and run:

```
python -m pip install --user pipenv
pipenv shell
pipenv update --dev
fab run
```

**Comment by KitchM** [comment]
/usr/bin/python: No module named pip


-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Jun 15, 2019, 7:19 AM by notifications@github.com:

**Comment by Jenyay** [comment]
Try to install pip with: dnf install python3-pip

**Comment by KitchM** [comment]
python3 -m pip install --user pipenv

Downloading/unpacking pipenv
  Downloading pipenv-2018.11.26.tar.gz (6.6MB): 6.6MB downloaded
  Running setup.py egg_info for package pipenv
    /usr/lib64/python3.3/distutils/dist.py:257: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    /usr/lib64/python3.3/distutils/dist.py:257: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    /usr/lib64/python3.3/distutils/dist.py:257: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "/usr/lib/python3.3/site-packages/setuptools/dist.py", line 80, in check_extras
        list(pkg_resources.parse_requirements(v))
      File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 2638, in parse_requirements
        line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
      File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 2606, in scan_list
        raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
    ValueError: ('Expected version spec in', 'pytest ~= 3.5', 'at', ' ~= 3.5')
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib64/python3.3/distutils/core.py", line 109, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3.3/site-packages/setuptools/dist.py", line 243, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python3.3/distutils/dist.py", line 261, in __init__
        self.finalize_options()
      File "/usr/lib/python3.3/site-packages/setuptools/dist.py", line 276, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python3.3/site-packages/setuptools/dist.py", line 83, in check_extras
        "'extras_require' must be a dictionary whose values are "
    distutils.errors.DistutilsSetupError: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 1016, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python3.3/site-packages/setuptools/sandbox.py", line 69, in run_setup
        lambda: execfile(
      File "/usr/lib/python3.3/site-packages/setuptools/sandbox.py", line 120, in run
        return func()
      File "/usr/lib/python3.3/site-packages/setuptools/sandbox.py", line 71, in <lambda>
        {'__file__':setup_script, '__name__':'__main__'}
      File "/usr/lib/python3.3/site-packages/setuptools/compat.py", line 94, in execfile
        exec_(compile(source, fn, 'exec'), globs, locs)
      File "setup.py", line 68, in <module>
    
      File "/usr/lib64/python3.3/distutils/core.py", line 115, in setup
        (attrs['name'], msg))
    SystemExit: error in parver setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip_build_xxx/pipenv/setup.py", line 152, in <module>
        cmdclass={"upload": UploadCommand, "deb": DebCommand},
      File "/usr/lib64/python3.3/distutils/core.py", line 109, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3.3/site-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python3.3/site-packages/setuptools/dist.py", line 263, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 568, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 806, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 818, in obtain
        return installer(requirement)
      File "/usr/lib/python3.3/site-packages/setuptools/dist.py", line 313, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 609, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 639, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 825, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 1031, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 1019, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error in parver setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
    Complete output from command python setup.py egg_info:
    /usr/lib64/python3.3/distutils/dist.py:257: UserWarning: Unknown distribution option: 'project_urls'

  warnings.warn(msg)

/usr/lib64/python3.3/distutils/dist.py:257: UserWarning: Unknown distribution option: 'long_description_content_type'

  warnings.warn(msg)

/usr/lib64/python3.3/distutils/dist.py:257: UserWarning: Unknown distribution option: 'python_requires'

  warnings.warn(msg)

Traceback (most recent call last):

  File "/usr/lib/python3.3/site-packages/setuptools/dist.py", line 80, in check_extras

    list(pkg_resources.parse_requirements(v))

  File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 2638, in parse_requirements

    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")

  File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 2606, in scan_list

    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])

ValueError: ('Expected version spec in', 'pytest ~= 3.5', 'at', ' ~= 3.5')



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/usr/lib64/python3.3/distutils/core.py", line 109, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python3.3/site-packages/setuptools/dist.py", line 243, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib64/python3.3/distutils/dist.py", line 261, in __init__

    self.finalize_options()

  File "/usr/lib/python3.3/site-packages/setuptools/dist.py", line 276, in finalize_options

    ep.load()(self, ep.name, value)

  File "/usr/lib/python3.3/site-packages/setuptools/dist.py", line 83, in check_extras

    "'extras_require' must be a dictionary whose values are "

distutils.errors.DistutilsSetupError: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/usr/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 1016, in run_setup

    run_setup(setup_script, args)

  File "/usr/lib/python3.3/site-packages/setuptools/sandbox.py", line 69, in run_setup

    lambda: execfile(

  File "/usr/lib/python3.3/site-packages/setuptools/sandbox.py", line 120, in run

    return func()

  File "/usr/lib/python3.3/site-packages/setuptools/sandbox.py", line 71, in <lambda>

    {'__file__':setup_script, '__name__':'__main__'}

  File "/usr/lib/python3.3/site-packages/setuptools/compat.py", line 94, in execfile

    exec_(compile(source, fn, 'exec'), globs, locs)

  File "setup.py", line 68, in <module>



  File "/usr/lib64/python3.3/distutils/core.py", line 115, in setup

    (attrs['name'], msg))

SystemExit: error in parver setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip_build_xxx/pipenv/setup.py", line 152, in <module>

    cmdclass={"upload": UploadCommand, "deb": DebCommand},

  File "/usr/lib64/python3.3/distutils/core.py", line 109, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python3.3/site-packages/setuptools/dist.py", line 239, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python3.3/site-packages/setuptools/dist.py", line 263, in fetch_build_eggs

    parse_requirements(requires), installer=self.fetch_build_egg

  File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 568, in resolve

    dist = best[req.key] = env.best_match(req, self, installer)

  File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 806, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 818, in obtain

    return installer(requirement)

  File "/usr/lib/python3.3/site-packages/setuptools/dist.py", line 313, in fetch_build_egg

    return cmd.easy_install(req)

  File "/usr/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 609, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/usr/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 639, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/usr/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 825, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/usr/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 1031, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/usr/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 1019, in run_setup

    raise DistutilsError("Setup script exited with %s" % (v.args[0],))

distutils.errors.DistutilsError: Setup script exited with error in parver setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_xxx/pipenv
Storing complete log in /home/xxx/.pip/pip.log

**Comment by KitchM** [comment]
Any further ideas?
