### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by novikov-nsa** [Jenyay/outwiker#495]
При запуске приложения на osx появилось следующее сообщение об ошибке

```
Traceback (most recent call last):
  File "/Users/sergejnovikov/PycharmProjects/outwiker/src/runoutwiker.py", line 42, in <module>
    locale = initLocale(outwiker_app.application.config)
  File "/Users/sergejnovikov/PycharmProjects/outwiker/src/outwiker/core/i18n.py", line 114, in initLocale
    init_i18n(language)
  File "/Users/sergejnovikov/PycharmProjects/outwiker/src/outwiker/core/i18n.py", line 36, in init_i18n
    lang = loadLanguage(language, langdir, u"outwiker")
  File "/Users/sergejnovikov/PycharmProjects/outwiker/src/outwiker/core/i18n.py", line 54, in loadLanguage
    lang = gettext.translation(domain,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/gettext.py", line 583, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/gettext.py", line 554, in find
    for nelang in _expand_lang(lang):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/gettext.py", line 213, in _expand_lang
    loc = locale.normalize(loc)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/locale.py", line 401, in normalize
    code = localename.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by novikov-nsa** [comment]
Вылечилось созданием файла outwiker.ini и указания в нем явным образом языка. 
Но получается есть ошибка- не создается ini-файл.
