### ISSUE TITLE
противоречия между CyHunspellwrapper и PyHunspell

### ISSUE THREAD

**Issue by AlexeiKharchev** [Jenyay/outwiker#499]
Попробуйте, пожалуйста, сами запустить проект из исходников (желательно на чистой системе)
AttributeError: module 'hunspell' has no attribute 'Hunspell'
у меня стоит Python 3.9.6 - cкомпилирован из исходников командами ./configure && make -j4 && sudo checkinstall

PS:
Программа замечательная, очень хочется присоединиться к Вашему проекту
пока придется пользоваться snap

**Comment by Jenyay** [comment]
А можно полное описание ошибки? Я не уверен, что удастся избавиться от CyHunspell, потому что это единственная обертка над hunspell, которая мне попалась, которая нормально собирается под Windows и Linux.

**Comment by AlexeiKharchev** [comment]
python3 src/runoutwiker.py 
wxPython language: LANGUAGE_RUSSIAN
Traceback (most recent call last):
  File "/media/C/Git_docs/outwiker/src/runoutwiker.py", line 67, in <module>
    starter.processGUI()
  File "/media/C/Git_docs/outwiker/src/outwiker/core/starter.py", line 52, in processGUI
    self.__openRecentWiki()
  File "/media/C/Git_docs/outwiker/src/outwiker/core/starter.py", line 94, in __openRecentWiki
    openWiki(self._application.recentWiki[0])
  File "/media/C/Git_docs/outwiker/src/outwiker/core/commands.py", line 231, in openWiki
    Application.wikiroot = result
  File "/media/C/Git_docs/outwiker/src/outwiker/core/application.py", line 407, in wikiroot
    self.onWikiOpen(self.__wikiroot)
  File "/media/C/Git_docs/outwiker/src/outwiker/core/event.py", line 54, in __call__
    handler[0](*args, **kwargs)
  File "/media/C/Git_docs/outwiker/src/outwiker/gui/tabscontroller.py", line 246, in __onWikiOpen
    self.__loadTabs(root)
  File "/media/C/Git_docs/outwiker/src/outwiker/gui/tabscontroller.py", line 222, in __loadTabs
    self._application.selectedPage = self._tabsCtrl.GetPage(selectedTab)
  File "/media/C/Git_docs/outwiker/src/outwiker/core/application.py", line 476, in selectedPage
    self.__wikiroot.selectedPage = page
  File "/media/C/Git_docs/outwiker/src/outwiker/core/tree.py", line 425, in selectedPage
    self.root.onPageSelect(self._selectedPage)
  File "/media/C/Git_docs/outwiker/src/outwiker/core/event.py", line 54, in __call__
    handler[0](*args, **kwargs)
  File "/media/C/Git_docs/outwiker/src/outwiker/core/event.py", line 54, in __call__
    handler[0](*args, **kwargs)
  File "/media/C/Git_docs/outwiker/src/outwiker/gui/currentpagepanel.py", line 102, in __onPageSelect
    self.__updatePageView(page)
  File "/media/C/Git_docs/outwiker/src/outwiker/gui/currentpagepanel.py", line 134, in __updatePageView
    self.__createPageView(page)
  File "/media/C/Git_docs/outwiker/src/outwiker/gui/currentpagepanel.py", line 153, in __createPageView
    self.__createConcretePageView(page)
  File "/media/C/Git_docs/outwiker/src/outwiker/gui/currentpagepanel.py", line 187, in __createConcretePageView
    pageView = factory.getPageView(self, self._application)
  File "/media/C/Git_docs/outwiker/src/outwiker/pages/wiki/wikipage.py", line 84, in getPageView
    return WikiPageView(parent, application)
  File "/media/C/Git_docs/outwiker/src/outwiker/pages/wiki/wikipageview.py", line 39, in __init__
    super(WikiPageView, self).__init__(parent, application)
  File "/media/C/Git_docs/outwiker/src/outwiker/pages/wiki/basewikipageview.py", line 24, in __init__
    super(BaseWikiPageView, self).__init__(parent, application)
  File "/media/C/Git_docs/outwiker/src/outwiker/pages/html/basehtmlpanel.py", line 51, in __init__
    self._codeEditor = self.getTextEditor()(self.notebook)
  File "/media/C/Git_docs/outwiker/src/outwiker/pages/wiki/wikieditor.py", line 17, in __init__
    super().__init__(parent)
  File "/media/C/Git_docs/outwiker/src/outwiker/gui/texteditor.py", line 71, in __init__
    self.setDefaultSettings()
  File "/media/C/Git_docs/outwiker/src/outwiker/pages/wiki/wikieditor.py", line 84, in setDefaultSettings
    super(WikiEditor, self).setDefaultSettings()
  File "/media/C/Git_docs/outwiker/src/outwiker/gui/texteditor.py", line 145, in setDefaultSettings
    self.getSpellChecker().skipWordsWithNumbers = self.config.spellSkipDigits.value
  File "/media/C/Git_docs/outwiker/src/outwiker/gui/texteditor.py", line 265, in getSpellChecker
    spellChecker = SpellChecker(langlist, spellDirList)
  File "/media/C/Git_docs/outwiker/src/outwiker/core/spellchecker/spellchecker.py", line 18, in __init__
    self._realChecker = getOS().getSpellChecker(langlist, folders)
  File "/media/C/Git_docs/outwiker/src/outwiker/core/system.py", line 199, in getSpellChecker
    return CyHunspellWrapper(langlist, folders)
  File "/media/C/Git_docs/outwiker/src/outwiker/core/spellchecker/cyhunspellwrapper.py", line 49, in __init__
    checker = hunspell.Hunspell(
AttributeError: module 'hunspell' has no attribute 'Hunspell'

**Comment by AlexeiKharchev** [comment]
в общем, закомментировал несколько строк в system.py и texteditor.py
сейчас запустилось

**Comment by lbm-services** [comment]
I have the same problem with the latest version, what is the solution?  
 ```
"/home/hli/PycharmProjects/outwiker/src/outwiker/core/spellchecker/cyhunspellwrapper.py", line 53, in __init__
    checker = hunspell.Hunspell(
AttributeError: module 'hunspell' has no attribute 'Hunspell'. Did you mean: 'HunSpell'?
```

**Comment by clach04** [comment]
Sorry I don't speak Russian, so apologies if this is a duplicate.

From source checkout, issuing:

    pip install -e .

works fine, BUT trying to run with:

    cd src
    python runoutwiker.py

Fails due to missing hunspell.

Adding hunspell to the toml file with `Python 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)] on win32` doesn't work as I'm missing a C compiler. As a quick hack I created `hunspell.py` which fakes out spelling:

```python
class Hunspell:
    def __init__(self, *args, **kwargs):
        pass

    def spell(self, word):
        return True  # just lie, the word is spelled completely fine ;-)

    def suggest(self, word):
        pass
```

This allows things to run 😆 

That's about as far as I got it allows trees to be edited and viewed BUT it essentially disables spell check. This looks like a cool tool 👍  but I'm likely to use it, now I found out the the file format (possibly related https://github.com/Jenyay/outwiker/issues/550 ?) as I'm working with existing directories of text files with file extension .txt and .md.

Hopefully this will help someone else if they hit similar issues with hunspell,
